### PR TITLE
Add support for Windows and aarch64

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by elbaro** [comment]
Can you add a basic file presence test for Windows/aarch64 in `meta.yml`?

**Comment by xhochy** [comment]
> Can you add a basic file presence test for Windows/aarch64 in `meta.yml`?

It's already there for aarch64 as it's also Linux, for Windows I'm working on it.

**Comment by xhochy** [comment]
For Windows, files are put in the wrong directories. So the test will fail. I'm going to work on a patch next week.

**Comment by xhochy** [comment]
@elbaro Ready for review, I've submitted the patch also upstream at https://github.com/microsoft/mimalloc/pull/255 and will work there with the author on integration so that we can get rid of it in the next release.

This also updates to 1.6.3 where we can explicitly disable the static build.

**Comment by elbaro** [comment]
oops, I think the build number should have been reset to 0.

**Comment by xhochy** [comment]
> oops, I think the build number should have been reset to 0.

Oh, yes! Not wild though. The other way round would be more annoying.

**Pull request merged**
